export const themeRefs = {
  '$brand-body-bg': ['body-bg'],
  '$brand-text-color': [
    'content-color',
    'component-outline-color',
    'component-outline-active-color',
  ],
  '$brand-disabled-color': ['content-disabled-color'],
  '$brand-error-color': ['content-required-color', 'content-error-color'],
  '$brand-hint-color': ['content-hint-color', 'link-weak-color'],
  '$brand-white': [
    'content-bg',
    'component-primary-color',
    'component-primary-hover-color',
    'component-primary-active-color',
    'component-outline-bg',
    'component-outline-hover-bg',
  ],
  '$brand-border-color': [
    'content-border-color',
    'component-outline-active-bg',
    'component-outline-border-color',
    'component-outline-active-border-color',
  ],
  '$brand-success-color': ['content-success-color'],
  '$brand-success-bg': ['content-success-bg'],
  '$brand-warning-color': ['content-warning-color'],
  '$brand-warning-bg': ['content-warning-bg'],
  '$brand-error-bg': ['content-error-bg'],
  '$brand-primary-color': [
    'link-color',
    'component-primary-bg',
    'component-primary-border-color',
    'component-outline-hover-color',
    'component-outline-hover-border-color',
  ],
  '$brand-primary-hover-color': [
    'link-hover-color',
    'link-weak-hover-color',
    'component-primary-hover-bg',
    'component-primary-hover-border-color',
  ],
  '$brand-primary-active-color': [
    'link-active-color',
    'link-weak-active-color',
    'component-primary-active-bg',
    'component-primary-active-border-color',
  ],
};
