export const themeRefs = {
  '$gray-500': ['body-color'],
  $white: ['body-bg', 'primary-color'],
  '$green-500': ['success-color', 'success-border-color'],
  '$green-100': ['success-bg'],
  '$orange-500': ['warning-color', 'warning-border-color'],
  '$orange-100': ['warning-bg'],
  '$red-500': ['danger-color', 'danger-border-color'],
  '$red-100': ['danger-bg'],
  '$blue-500': ['link-color'],
  '$blue-400': ['link-hover-color', 'weak-hover-color'],
  '$blue-600': ['link-active-color', 'weak-active-color'],
  '$primary-500': [
    'default-hover-color',
    'default-hover-border-color',
    'primary-bg',
    'primary-border-color',
  ],
  '$primary-100': ['default-hover-bg'],
  '$section-bg': ['default-selected', 'default-disabled-bg'],
  '$disabled-color': [
    'default-disabled-color',
    'default-disabled-border-color',
  ],
  '$primary-400': ['primary-hover-bg', 'primary-hover-border-color'],
  '$primary-600': ['primary-active-bg', 'primary-active-border-color'],
  '$hint-color': ['weak-color'],
  '$yellow-500': ['rate-star-bg'],
};
