export const themeRefs = {
  '$brand-text-default': [
    'text-info',
    'text-alt-behavior-default',
    'text-alt-behavior-active',
    'text-weak-behavior',
  ],
  '$brand-text-disabled': ['text-disabled', 'text-icon-disabled'],
  '$brand-error': [
    'text-required',
    'text-destructive',
    'text-error',
    'text-icon-error',
    'border-error',
  ],
  '$brand-primary-default': [
    'text-primary',
    'text-link',
    'text-alt-behavior-hover',
    'background-behavior-default',
    'border-behavior-default',
    'border-alt-behavior-hover',
  ],
  '$brand-text-weak': ['text-weak', 'text-icon', 'text-weak-link', 'text-hint'],
  '$brand-success': ['text-success', 'text-icon-success', 'border-success'],
  '$brand-warn': ['text-warn', 'text-icon-warn', 'border-warn'],
  '$brand-primary-hover': [
    'text-link-hover',
    'text-weak-link-hover',
    'background-behavior-hover',
    'border-behavior-hover',
  ],
  '$brand-primary-active': [
    'text-link-active',
    'text-weak-link-active',
    'background-behavior-active',
    'border-behavior-active',
  ],
  '$brand-text-drak-default': ['text-behavior'],
  '$brand-background-default': [
    'background-info',
    'background-disabled',
    'border-disabled',
  ],
  '$brand-background-alt': [
    'background-alt',
    'background-alt-behavior-default',
    'background-alt-behavior-hover',
  ],
  '$brand-background-success': ['background-success'],
  '$brand-background-warn': ['background-warn'],
  '$brand-background-error': ['background-error'],
  '$brand-background-highlight': ['background-alt-behavior-active'],
  '$brand-border-default': [
    'border-info',
    'border-separator',
    'border-alt-behavior-default',
    'border-alt-behavior-active',
  ],
};
