/**
 *  Auto generated by `plugins/postcss-generate-css-var-ref.js`.
 *  Describe the relationship between variables and css variables
 *  DO NOT EDIT
 */

export const cssVarInfo = [
  {
    cssVariableName: '--theme-link-color',
    color: '$primary-500',
    comments: ' Primary text link brand color',
  },
  {
    cssVariableName: '--theme-link-hover-color',
    color: '$primary-400',
    comments: ' Hover state of primary text link brand color',
  },
  {
    cssVariableName: '--theme-link-active-color',
    color: '$primary-600',
    comments: ' Active state of primary text link brand color',
  },
  {
    cssVariableName: '--theme-default-hover-color',
    color: '$primary-500',
    comments:
      ' Hover state of default text color components e.g. default button..',
  },
  {
    cssVariableName: '--theme-default-hover-bg',
    color: '$primary-100',
    comments:
      ' Hover state of default background color of components , e.g. grid, select panel..',
  },
  {
    cssVariableName: '--theme-default-hover-border-color',
    color: '$primary-500',
    comments:
      ' Hover state of default border color of components , e.g. default button..',
  },
  {
    cssVariableName: '--theme-primary-bg',
    color: '$primary-500',
    comments:
      ' Primary background color of components, e.g. primary type button',
  },
  {
    cssVariableName: '--theme-primary-border-color',
    color: '$primary-500',
    comments: ' Primary border color of components, e.g. primary type button',
  },
  {
    cssVariableName: '--theme-primary-hover-bg',
    color: '$primary-400',
    comments:
      ' Hover state of primary background color of components, e.g. primary type button',
  },
  {
    cssVariableName: '--theme-primary-hover-border-color',
    color: '$primary-400',
    comments:
      ' Hover state of primary border color of components, e.g. primary type button',
  },
  {
    cssVariableName: '--theme-primary-active-bg',
    color: '$primary-600',
    comments:
      ' Active state of primary background color of components, e.g. primary type button',
  },
  {
    cssVariableName: '--theme-primary-active-border-color',
    color: '$primary-600',
    comments:
      ' Active state of primary border color of components, e.g. primary type button',
  },
  {
    cssVariableName: '--theme-weak-hover-color',
    color: '$primary-400',
    comments: ' Hover state of primary text weak link brand color',
  },
  {
    cssVariableName: '--theme-weak-active-color',
    color: '$primary-600',
    comments: ' Active state of primary text weak link brand color',
  },
];
