/**
 *  Auto generated by `plugins/postcss-generate-css-var-ref.js`.
 *  Describe the one-to-many relationship between variables and css variables
 *  DO NOT EDIT
 */

export const cssVarRef = {
  '$text-600': ['--theme-title-color', '--theme-body-color'],
  '$text-500': ['--theme-hint-color', '--theme-weak-color'],
  '$text-400': [
    '--theme-disabled-color',
    '--theme-default-disabled-color',
    '--theme-default-disabled-border-color',
  ],
  '$text-200': [
    '--theme-section-bg',
    '--theme-default-selected',
    '--theme-default-disabled-bg',
  ],
  '$shadow-color': ['--theme-section-shadow'],
  '$text-300': ['--theme-section-border-color'],
  '$text-100': ['--theme-body-bg', '--theme-primary-color'],
  '$success-500': ['--theme-success-color', '--theme-success-border-color'],
  '$success-100': ['--theme-success-bg'],
  '$warning-500': ['--theme-warning-color', '--theme-warning-border-color'],
  '$warning-100': ['--theme-warning-bg'],
  '$danger-500': ['--theme-danger-color', '--theme-danger-border-color'],
  '$danger-100': ['--theme-danger-bg'],
  '$primary-500': [
    '--theme-link-color',
    '--theme-default-hover-color',
    '--theme-default-hover-border-color',
    '--theme-primary-bg',
    '--theme-primary-border-color',
  ],
  '$primary-400': [
    '--theme-link-hover-color',
    '--theme-primary-hover-bg',
    '--theme-primary-hover-border-color',
    '--theme-weak-hover-color',
  ],
  '$primary-600': [
    '--theme-link-active-color',
    '--theme-primary-active-bg',
    '--theme-primary-active-border-color',
    '--theme-weak-active-color',
  ],
  '$primary-100': ['--theme-default-hover-bg'],
  '$star-color': ['--theme-rate-bg'],
};

export const cssRgbVarRef = {
  '$text-600': ['--theme-rgb-title-color', '--theme-rgb-body-color'],
  '$text-500': ['--theme-rgb-hint-color', '--theme-rgb-weak-color'],
  '$text-400': [
    '--theme-rgb-disabled-color',
    '--theme-rgb-default-disabled-color',
    '--theme-rgb-default-disabled-border-color',
  ],
  '$text-200': [
    '--theme-rgb-section-bg',
    '--theme-rgb-default-selected',
    '--theme-rgb-default-disabled-bg',
  ],
  '$shadow-color': ['--theme-rgb-section-shadow'],
  '$text-300': ['--theme-rgb-section-border-color'],
  '$text-100': ['--theme-rgb-body-bg', '--theme-rgb-primary-color'],
  '$success-500': [
    '--theme-rgb-success-color',
    '--theme-rgb-success-border-color',
  ],
  '$success-100': ['--theme-rgb-success-bg'],
  '$warning-500': [
    '--theme-rgb-warning-color',
    '--theme-rgb-warning-border-color',
  ],
  '$warning-100': ['--theme-rgb-warning-bg'],
  '$danger-500': [
    '--theme-rgb-danger-color',
    '--theme-rgb-danger-border-color',
  ],
  '$danger-100': ['--theme-rgb-danger-bg'],
  '$primary-500': [
    '--theme-rgb-link-color',
    '--theme-rgb-default-hover-color',
    '--theme-rgb-default-hover-border-color',
    '--theme-rgb-primary-bg',
    '--theme-rgb-primary-border-color',
  ],
  '$primary-400': [
    '--theme-rgb-link-hover-color',
    '--theme-rgb-primary-hover-bg',
    '--theme-rgb-primary-hover-border-color',
    '--theme-rgb-weak-hover-color',
  ],
  '$primary-600': [
    '--theme-rgb-link-active-color',
    '--theme-rgb-primary-active-bg',
    '--theme-rgb-primary-active-border-color',
    '--theme-rgb-weak-active-color',
  ],
  '$primary-100': ['--theme-rgb-default-hover-bg'],
  '$star-color': ['--theme-rgb-rate-bg'],
};
