scss_files: sass/**/*.scss
plugin_directories:
  - .scss-linters
plugin_gems: []
severity: warning
linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false
  BemDepth:
    enabled: false
    max_elements: 1
  BorderZero:
    enabled: true
    convention: zero
  ChainedClasses:
    enabled: false
  ColorKeyword:
    enabled: false
  ColorVariable:
    enabled: false
  Comment:
    enabled: false
  DebugStatement:
    enabled: false
  DeclarationOrder:
    enabled: true
  DisableLinterReason:
    enabled: false
  DuplicateProperty:
    enabled: true
  ElsePlacement:
    enabled: true
    style: same_line
  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true
  EmptyRule:
    enabled: true
  ExtendDirective:
    enabled: false
  FinalNewline:
    enabled: true
    present: true
  HexLength:
    enabled: true
    style: short
  HexNotation:
    enabled: true
    style: lowercase
  HexValidation:
    enabled: true
  IdSelector:
    enabled: false
  ImportantRule:
    enabled: false
  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false
  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space
    width: 4
  LeadingZero:
    enabled: true
    style: exclude_zero
  MergeableSelector:
    enabled: true
    force_nesting: true
  NameFormat:
    enabled: true
    allow_leading_underscore: true
    convention: hyphenated_lowercase
  NestingDepth:
    enabled: true
    max_depth: 7
    ignore_parent_selectors: false
  PlaceholderInExtend:
    enabled: true
  PropertyCount:
    enabled: false
    include_nested: false
    max_properties: 10
  PropertySortOrder:
    enabled: false
    ignore_unspecified: false
    min_properties: 2
    separate_groups: false
  PropertySpelling:
    enabled: true
    extra_properties: []
    disabled_properties: []
  PropertyUnits:
    enabled: true
    global:
      - ch
      - em
      - ex
      - rem
      - cm
      - in
      - mm
      - pc
      - pt
      - px
      - q
      - vh
      - vw
      - vmin
      - vmax
      - deg
      - grad
      - rad
      - turn
      - ms
      - s
      - Hz
      - kHz
      - dpi
      - dpcm
      - dppx
      - '%'
    properties: {}
  PseudoElement:
    enabled: true
  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: true
    allow_element_with_id: false
  SelectorDepth:
    enabled: true
    max_depth: 7
  SelectorFormat:
    enabled: true
    convention: hyphenated_lowercase
  Shorthand:
    enabled: true
    allowed_shorthands:
      - 1
      - 2
      - 3
  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true
  SingleLinePerSelector:
    enabled: true
  SpaceAfterComma:
    enabled: true
    style: one_space
  SpaceAfterPropertyColon:
    enabled: true
    style: one_space
  SpaceAfterPropertyName:
    enabled: true
  SpaceAfterVariableName:
    enabled: true
  SpaceAroundOperator:
    enabled: true
    style: one_space
  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: false
  SpaceBetweenParens:
    enabled: true
    spaces: 0
  StringQuotes:
    enabled: true
    style: single_quotes
  TrailingSemicolon:
    enabled: true
  TrailingWhitespace:
    enabled: true
  TrailingZero:
    enabled: true
  TransitionAll:
    enabled: true
  UnnecessaryMantissa:
    enabled: true
  UnnecessaryParentReference:
    enabled: true
  UrlFormat:
    enabled: true
  UrlQuotes:
    enabled: true
  VariableForProperty:
    enabled: false
    properties: []
  VendorPrefix:
    enabled: true
    identifier_list: base
    additional_identifiers: []
    excluded_identifiers: []
  ZeroUnit:
    enabled: true
  'Compass::*':
    enabled: false
