name: Check deadlinks in docs

on:
  schedule:
    - cron: '0 21 * * *' # At 21:00

  workflow_dispatch:

jobs:
  check-deadlink:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn --frozen-lockfile
      - run: yarn workspace zent check-deadlink
