name: 'CI'

on:
  push:
    branches:
      - master
      - v[0-9]+
  pull_request:
    branches:
      - master
      - v[0-9]+

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn lint

  check-git-hooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn check-git-hooks
