name: Update caniuse-lite database

on:
  schedule:
    - cron: '0 3 * * 6' # At 03:00 on Saturday

  workflow_dispatch:

jobs:
  update-caniuse-lite-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn build # generate `dependency-graph.json` which is used in pre-push hook
      - run: npx browserslist@latest --update-db
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        env:
          HUSKY: 0
        with:
          title: 'Automatic update of caniuse-lite database'
          body: 'This PR updates caniuse-lite database to its latest version'
          commit-message: '[github_action] update caniuse-lite database'
          delete-branch: true
          base: master
