name: Update caniuse-lite database

on:
  schedule:
    - cron: '0 3 * * 6' # At 03:00 on Saturday

  workflow_dispatch:

jobs:
  update-caniuse-lite-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Use Node.js '14'
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn --frozen-lockfile
      - run: yarn build # generate `dependency-graph.json` which is used in pre-push hook
      - run: npx browserslist@latest --update-db
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Automatic update of caniuse-lite database'
          body: 'This PR updates caniuse-lite database to its latest version'
          commit-message: '[github_action] update caniuse-lite database'
          delete-branch: true
          base: master
